-- MySQL Script generated by MySQL Workbench
-- 01/04/15 21:25:39
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbproj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbproj` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbproj` ;

-- -----------------------------------------------------
-- Table `dbproj`.`salutations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`salutations` (
  `salutations_ID` INT UNSIGNED NOT NULL,
  `salutations_name` VARCHAR(45) NULL,
  PRIMARY KEY (`salutations_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`countrys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`countrys` (
  `countrys_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `countrys_name` VARCHAR(45) NULL,
  PRIMARY KEY (`countrys_ID`),
  UNIQUE INDEX `countrys_ID_UNIQUE` (`countrys_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`roles` (
  `roles_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `roles_name` VARCHAR(45) NULL,
  PRIMARY KEY (`roles_ID`),
  UNIQUE INDEX `roles_ID_UNIQUE` (`roles_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`users` (
  `user_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_salutation` INT UNSIGNED NOT NULL,
  `user_nickname` VARCHAR(45) NULL,
  `user_password` VARCHAR(45) NULL,
  `user_firstname` VARCHAR(45) NULL,
  `user_lastname` VARCHAR(45) NULL,
  `user_adress` VARCHAR(45) NULL,
  `user_housenumber` VARCHAR(45) NULL,
  `user_city` VARCHAR(45) NULL,
  `user_postcode` VARCHAR(45) NULL,
  `user_country` INT UNSIGNED NOT NULL,
  `user_role` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_ID`),
  UNIQUE INDEX `user_ID_UNIQUE` (`user_ID` ASC),
  INDEX `fk_users_salutations_idx` (`user_salutation` ASC),
  INDEX `fk_users_countrys1_idx` (`user_country` ASC),
  INDEX `fk_users_roles1_idx` (`user_role` ASC),
  CONSTRAINT `fk_users_salutations`
    FOREIGN KEY (`user_salutation`)
    REFERENCES `dbproj`.`salutations` (`salutations_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_countrys1`
    FOREIGN KEY (`user_country`)
    REFERENCES `dbproj`.`countrys` (`countrys_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`user_role`)
    REFERENCES `dbproj`.`roles` (`roles_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`directors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`directors` (
  `directors_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `director_firstname` VARCHAR(45) NULL,
  `director_lastname` VARCHAR(45) NULL,
  PRIMARY KEY (`directors_ID`),
  UNIQUE INDEX `directors_ID_UNIQUE` (`directors_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`genres` (
  `genre_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NULL,
  PRIMARY KEY (`genre_ID`),
  UNIQUE INDEX `genres_ID_UNIQUE` (`genre_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`publishers` (
  `publisher_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `publisher_name` VARCHAR(45) NULL,
  PRIMARY KEY (`publisher_ID`),
  UNIQUE INDEX `publisher_ID_UNIQUE` (`publisher_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`agelimits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`agelimits` (
  `agelimit_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `agelimit_name` VARCHAR(45) NULL,
  PRIMARY KEY (`agelimit_ID`),
  UNIQUE INDEX `agelimit_ID_UNIQUE` (`agelimit_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`articles` (
  `article_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `article_title` VARCHAR(45) NULL,
  `article_director` INT UNSIGNED NOT NULL,
  `article_genre` INT UNSIGNED NOT NULL,
  `article_runtime` VARCHAR(45) NULL,
  `article_publisher` INT UNSIGNED NOT NULL,
  `article_agelimit` INT UNSIGNED NOT NULL,
  `article_releasedate` DATE NULL,
  `article_publishingdate` DATE NULL,
  `article_amount` INT NULL,
  `article_rentprice` DOUBLE NULL,
  `article_purchaseprice` DOUBLE NULL,
  PRIMARY KEY (`article_ID`),
  UNIQUE INDEX `article_ID_UNIQUE` (`article_ID` ASC),
  INDEX `fk_articles_directors1_idx` (`article_director` ASC),
  INDEX `fk_articles_genres1_idx` (`article_genre` ASC),
  INDEX `fk_articles_publishers1_idx` (`article_publisher` ASC),
  INDEX `fk_articles_agelimits1_idx` (`article_agelimit` ASC),
  CONSTRAINT `fk_articles_directors1`
    FOREIGN KEY (`article_director`)
    REFERENCES `dbproj`.`directors` (`directors_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_genres1`
    FOREIGN KEY (`article_genre`)
    REFERENCES `dbproj`.`genres` (`genre_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_publishers1`
    FOREIGN KEY (`article_publisher`)
    REFERENCES `dbproj`.`publishers` (`publisher_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_agelimits1`
    FOREIGN KEY (`article_agelimit`)
    REFERENCES `dbproj`.`agelimits` (`agelimit_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`purchasedarticles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`purchasedarticles` (
  `purchasedarticles_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `purchasedarticles_articles` INT UNSIGNED NOT NULL,
  `purchasedarticles_timestamp` TIMESTAMP NULL,
  PRIMARY KEY (`purchasedarticles_ID`),
  UNIQUE INDEX `purchasedarticles_ID_UNIQUE` (`purchasedarticles_ID` ASC),
  INDEX `fk_purchasedarticles_articles1_idx` (`purchasedarticles_articles` ASC),
  CONSTRAINT `fk_purchasedarticles_articles1`
    FOREIGN KEY (`purchasedarticles_articles`)
    REFERENCES `dbproj`.`articles` (`article_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`purchasetype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`purchasetype` (
  `purchasetype_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `purchasetype_name` VARCHAR(45) NULL,
  PRIMARY KEY (`purchasetype_ID`),
  UNIQUE INDEX `purchasetype_ID_UNIQUE` (`purchasetype_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`purchasesettlements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`purchasesettlements` (
  `purchasesettlements_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `purchasesettlements_purchasedarticles` INT UNSIGNED NOT NULL,
  `purchasesettlements_userID` INT UNSIGNED NOT NULL,
  `purchasesettlements_date` DATE NOT NULL,
  `purchasesettlements_purchasetype` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`purchasesettlements_ID`),
  UNIQUE INDEX `purchasesettlements_ID_UNIQUE` (`purchasesettlements_ID` ASC),
  INDEX `fk_purchasesettlements_purchasedarticles1_idx` (`purchasesettlements_purchasedarticles` ASC),
  INDEX `fk_purchasesettlements_purchasetype1_idx` (`purchasesettlements_purchasetype` ASC),
  INDEX `fk_purchasesettlements_users1_idx` (`purchasesettlements_userID` ASC),
  CONSTRAINT `fk_purchasesettlements_purchasedarticles1`
    FOREIGN KEY (`purchasesettlements_purchasedarticles`)
    REFERENCES `dbproj`.`purchasedarticles` (`purchasedarticles_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchasesettlements_purchasetype1`
    FOREIGN KEY (`purchasesettlements_purchasetype`)
    REFERENCES `dbproj`.`purchasetype` (`purchasetype_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchasesettlements_users1`
    FOREIGN KEY (`purchasesettlements_userID`)
    REFERENCES `dbproj`.`users` (`user_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbproj`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbproj`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
